{{- if ((.Values.networking).expose) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{ template "app-environment-suffix" .}}
  labels:
    app: {{ .Release.Name }}{{ template "app-environment-suffix" .}}
spec:
  type: {{ .Values.networking.type | default "ClusterIP" }}
  ports:
    - port: {{ (.Values.networking).port }}
      targetPort: {{ (.Values.networking).port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
  {{- end }}
